apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: maas-gateway-auth-policy
  namespace: openshift-ingress
  annotations:
    opendatahub.io/managed: "false"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-gateway
  rules:
    metadata:
      matchedTier:
        http:
          url: http://maas-api.maas-api.svc.cluster.local:8080/v1/tiers/lookup
          contentType: application/json
          method: POST
          body:
            expression: '{ "groups": auth.identity.user.groups }'
        cache:
          key:
            selector: auth.identity.user.username
          ttl: 300
    authentication:
      service-accounts:
        kubernetesTokenReview:
          audiences:
            - maas-gateway
        defaults:
          userid:
            expression: 'auth.identity.user.username.split(":")[3]'
        cache:
          key:
            selector: context.request.http.headers.authorization.@case:lower
          ttl: 600
    authorization:
      tier-access:
        cache:
          key:
            selector: "{auth.identity.user.username}:{request.path}"
          ttl: 60
        kubernetesSubjectAccessReview:
          user:
            expression: auth.identity.user.username
          authorizationGroups:
            expression: auth.identity.user.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            resource:
              value: llminferenceservices
            namespace:
              expression: 'request.path.split("/")[1]'
            name:
              expression: 'request.path.split("/")[2]'
            verb:
              value: post
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  expression: auth.identity.userid
                tier:
                  expression: auth.metadata.matchedTier["tier"]

